name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Hugo
        run: ./setup-hugo.sh
        
      - name: Build site
        run: ./hugo
      
      - name: Package output
        run: cd public && zip -r ../site.zip .
      
      - name: Upload package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: site-package
          path: site.zip
  
  deploy:
    name: Deploy to AWS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: site-package
        
      - name: Deploy to AWS
        uses: luisgreen/amplify_deployment@main
        with:
          appId: ${{ secrets.AWS_APP_ID }}
          branchName: ${{ secrets.AWS_APP_BRANCH_NAME }}
          artifactPath: ./site.zip
          region: ${{ secrets.AWS_APP_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
